### ISSUE TITLE
RSS 地址无效

### ISSUE THREAD

**Issue by tuliren** [sjtuer/sjtuer.github.io#1]
博主你好，能否修复一下贵博客的 RSS 地址？目前的 RSS 链接是无效的：
https://blog.syh.rocks/atom.xml

**Comment by sjtuer** [comment]
> 博主你好，能否修复一下贵博客的 RSS 地址？目前的 RSS 链接是无效的：
> https://blog.syh.rocks/atom.xml

哈哈，该项目只是用来测试HEXO在github上的部署，并不会真的发布文章。
HEXO RSS插件没有安装，页面中存在RSS超链接确实是个问题

**Comment by tuliren** [comment]
可惜可惜，注册了个 d 炸天的网址，结果只是测试……
